[picar]
# Raspberry Pi running PiCar-X
picar ansible_host=192.168.1.100 ansible_user=pi ansible_ssh_private_key_file=~/.ssh/id_rsa

# Example with different IP
# picar ansible_host=192.168.1.101 ansible_user=pi

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'